### PR TITLE
Implement ACK feature and follow best practice to avoid device non-responsiveness

### PR DESCRIPTION
**Pull request by eecharlie**
I've added library functions for using the interrupt feature of the device, and in turn used those functions to follow best practice of clearing a possible interrupt condition before every update to the device configuration. As noted in comments, the datasheet (rev. 1.7) p. 7 mentions this.

This change is meant to address the issue I raised in your project, although it does not include a unit test that actually reproduces the infrequently-occurring problem caused by the device initializing to a command register state with the interrupt enabled and then triggering.

The reason for this is that I've found the device to cause I2C bus lockups after a power cycle, and a cold boot is needed to cause possibly problematic initialization of the configuration register. I have yet to resolve the power cycling lockup issue.

Summary of impact: 

- Library now follows best practice for device communication
- Adafruit's example code is untouched and functions as it did before
- No existing library function signatures have been changed
- All new unit tests pass.
- The new library dependency (AUnit) is only needed to run the unit tests

### CODE REVIEW

**Comment by ladyada** [comment]
looks good, what hardware did you try this with?

**Comment by eecharlie** [comment]
A RedBoard (sorry had it laying around!) / Uno compatible

**Comment by eecharlie** [comment]
Looks like I made Travis happy. Anything else?

Side note, UV measurement accuracy depends on integration time which depends on Rset, so hopefully you're using 1% tolerance 270k resistors in your BOM :)

**Comment by ladyada** [comment]
yep we use 1%

**Comment by ladyada** [comment]
ill merge, lets see how it goes :)

**Comment by eecharlie** [comment]
Awesome. If it's Limor at the keyboard over there, it's an honor.

**Comment by ladyada** [comment]
huzzah!

**Pull request merged**
